# Generated by Django 4.2.1 on 2023-12-16 12:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Recruiter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new', models.BooleanField(default=True)),
                ('month_year', models.CharField(default='2023-12', help_text='Format: YYYY-MM', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_year_month', message='Format must be YYYY-MM', regex='^\\d{4}-\\d{2}$')])),
                ('jobpost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Recruiter.jobpost')),
            ],
        ),
    ]
