# Generated by Django 4.2.1 on 2023-12-16 12:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('postion_name', models.CharField(max_length=200)),
                ('organaization', models.CharField(max_length=200)),
                ('organaization_logo', models.ImageField(blank=True, default='jobpost.jpg', null=True, upload_to='')),
                ('job_brief', models.CharField(max_length=200, null=True)),
                ('Requirements_and_skills', models.TextField(null=True)),
                ('soft_skills', models.TextField(null=True)),
                ('Responsibilities', models.TextField(null=True)),
                ('contact_email', models.EmailField(max_length=254, null=True)),
                ('average_salary', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('month_year', models.CharField(default='2023-12', help_text='Format: YYYY-MM', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_year_month', message='Format must be YYYY-MM', regex='^\\d{4}-\\d{2}$')])),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TopCandidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recruiter.jobpost')),
            ],
        ),
    ]
