# Generated by Django 4.2.1 on 2023-12-16 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Recruiter', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topcandidates',
            name='seekers',
            field=models.ManyToManyField(to='accounts.seeker'),
        ),
        migrations.AddField(
            model_name='offers',
            name='jobpost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Recruiter.jobpost'),
        ),
        migrations.AddField(
            model_name='offers',
            name='seeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.seeker'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.city'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.knowledgearea'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Recruiter.jobtype'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.recruiter'),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='skill_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.knowledgearea'),
        ),
    ]
